DROP MCP SERVER IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.HELLO_WORLD_PRO_MCP;
DROP AGENT IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.HELLO_WORLD_PRO_AGENT;
DROP MCP SERVER IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.SEMANTIC_VIEWS_MCP;
DROP MCP SERVER IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.INVOCATION_POC_MCP;
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.HELLO_WORLD_TOOL(VARCHAR);
