-- Shared memory for the Haven data agents (backs KNOWLEDGE_AGENT).
-- One row per atomic observation; recall = cosine similarity on an arctic embedding,
-- so a note is recallable the moment it is written (no search-service refresh lag).

CREATE TABLE IF NOT EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_MEMORY (
    MEMORY_ID     VARCHAR       NOT NULL,
    CREATED_AT    TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY    VARCHAR       NOT NULL DEFAULT CURRENT_USER(),
    DOMAIN        VARCHAR       NOT NULL,           -- arrivals | bookings | general
    TOPIC         VARCHAR       NOT NULL,           -- short label, e.g. "grain of FCT_PARK_ARRIVAL"
    OBSERVATION   VARCHAR       NOT NULL,           -- the self-contained fact
    SOURCE_AGENT  VARCHAR,                          -- agent that asked for it to be recorded
    IS_ACTIVE     BOOLEAN       NOT NULL DEFAULT TRUE,
    RETIRED_AT    TIMESTAMP_LTZ,
    RETIRED_REASON VARCHAR,
    EMBEDDING     VECTOR(FLOAT, 1024)
);

CREATE OR REPLACE PROCEDURE HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.REMEMBER_OBSERVATION(
    DOMAIN VARCHAR, TOPIC VARCHAR, OBSERVATION VARCHAR, SOURCE_AGENT VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    new_id VARCHAR DEFAULT UUID_STRING();
BEGIN
    IF (LOWER(:DOMAIN) NOT IN ('arrivals', 'bookings', 'general')) THEN
        RETURN 'ERROR: domain must be one of arrivals, bookings, general';
    END IF;
    INSERT INTO HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_MEMORY
        (MEMORY_ID, DOMAIN, TOPIC, OBSERVATION, SOURCE_AGENT, EMBEDDING)
    SELECT :new_id, LOWER(:DOMAIN), :TOPIC, :OBSERVATION, :SOURCE_AGENT,
           SNOWFLAKE.CORTEX.EMBED_TEXT_1024('snowflake-arctic-embed-l-v2.0', :TOPIC || ': ' || :OBSERVATION);
    RETURN 'stored memory_id=' || new_id;
END;
$$;

CREATE OR REPLACE PROCEDURE HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.RECALL_OBSERVATIONS(
    QUERY VARCHAR, DOMAIN VARCHAR, TOP_K NUMBER)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    result VARCHAR;
BEGIN
    SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT(
               'memory_id', MEMORY_ID, 'domain', DOMAIN, 'topic', TOPIC, 'observation', OBSERVATION,
               'created_at', TO_VARCHAR(CREATED_AT, 'YYYY-MM-DD HH24:MI'), 'source_agent', SOURCE_AGENT,
               'similarity', ROUND(SCORE, 3)))
             WITHIN GROUP (ORDER BY SCORE DESC)::VARCHAR, '[]')
      INTO :result
      FROM (
        SELECT m.*, VECTOR_COSINE_SIMILARITY(m.EMBEDDING,
                   SNOWFLAKE.CORTEX.EMBED_TEXT_1024('snowflake-arctic-embed-l-v2.0', :QUERY)) AS SCORE
          FROM HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_MEMORY m
         WHERE m.IS_ACTIVE
           AND (COALESCE(LOWER(:DOMAIN), 'all') IN ('all', '') OR m.DOMAIN IN (LOWER(:DOMAIN), 'general'))
        QUALIFY ROW_NUMBER() OVER (ORDER BY SCORE DESC) <= LEAST(GREATEST(COALESCE(:TOP_K, 8), 1), 25)
      );
    RETURN result;
END;
$$;

CREATE OR REPLACE PROCEDURE HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.RETIRE_OBSERVATION(
    MEMORY_ID VARCHAR, REASON VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    UPDATE HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_MEMORY
       SET IS_ACTIVE = FALSE, RETIRED_AT = CURRENT_TIMESTAMP(), RETIRED_REASON = :REASON
     WHERE MEMORY_ID = :MEMORY_ID AND IS_ACTIVE;
    RETURN IFF(SQLROWCOUNT = 1, 'retired memory_id=' || :MEMORY_ID, 'ERROR: no active memory with id ' || :MEMORY_ID);
END;
$$;
