-- Removes everything created by 01-06. AGENT_MEMORY / AGENT_CALL_LOG are kept unless
-- the last two statements are uncommented.
DROP AGENT IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.HAVEN_MASTER_AGENT;
DROP AGENT IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ARRIVALS_AGENT;
DROP AGENT IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.BOOKINGS_AGENT;
DROP AGENT IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.KNOWLEDGE_AGENT;
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ASK_ARRIVALS_AGENT(VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ASK_BOOKINGS_AGENT(VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ASK_ARRIVALS_AGENT_THREADED(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ASK_BOOKINGS_AGENT_THREADED(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.ASK_KNOWLEDGE_AGENT(VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.RUN_AGENT(VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.REMEMBER_OBSERVATION(VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.RECALL_OBSERVATIONS(VARCHAR, VARCHAR, NUMBER);
DROP PROCEDURE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.RETIRE_OBSERVATION(VARCHAR, VARCHAR);
-- DROP TABLE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_MEMORY;
-- DROP TABLE IF EXISTS HAVEN_DATA_SCIENCE_DEV.PETERZENTAI_LOCAL.AGENT_CALL_LOG;
