DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_7_ORCHESTRATOR;
DROP MCP SERVER IF EXISTS {{DB}}.{{SCHEMA}}.SV_PANDAS_AGENT_MCP;
DROP PROCEDURE IF EXISTS {{DB}}.{{SCHEMA}}.ASK_PANDAS_AGENT_THREADED(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS {{DB}}.{{SCHEMA}}.RUN_AGENT(VARCHAR, VARCHAR, VARCHAR);
-- AGENT_CALL_LOG is kept (like agent-orchestration): drop it by hand if wanted.
DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_6_ANALYST_PYTHON;
DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_5_PANDAS;
DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_4_CODE_MINIMAL;
DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_2_RUN_SQL;
DROP MCP SERVER IF EXISTS {{DB}}.{{SCHEMA}}.SV_SQL_MCP;
DROP AGENT IF EXISTS {{DB}}.{{SCHEMA}}.SV_AGENT_1_ANALYST;
DROP SEMANTIC VIEW IF EXISTS {{DB}}.{{SCHEMA}}.FOOTFALL_ARRIVALS_SV_V3;
DROP VIEW IF EXISTS {{DB}}.{{SCHEMA}}.FOOTFALL_SV_OWNER_DAYS_V3;
DROP VIEW IF EXISTS {{DB}}.{{SCHEMA}}.FOOTFALL_SV_PARK_DAYS_V3;
DROP VIEW IF EXISTS {{DB}}.{{SCHEMA}}.FOOTFALL_SV_GUEST_DAYS_V3;
